package com.example.rpcprotocol;

public enum RequestType {
    GET_USERS,SAVE_REZERVARE, GET_CURSE, GET_REZERVARI, GET_REZERVARI_BY_ID_CURSA, UPDATE_CURSA, NEW_MESSAGE, LOGIN, LOGOUT, GET_USER_BY_USERNAME;
}
